---
# vars file for L1

hostname: L1

layer3_physical_interfaces: &l3
  - interface: ethernet1/11
    description: To S1 Eth1/1
    mode: layer3
    ip_address: 10.1.1.1
    mask: 31
    mtu: 9216
  - interface: ethernet1/12
    description: To S2 Eth1/1
    mode: layer3
    ip_address: 10.2.2.1
    mask: 31
    mtu: 9216

layer2_physical_interfaces: &l2
    - interface: ethernet1/1
      description: To Server1
      mtu: 9216
    - interface: ethernet1/2
      description: To Server2
      mtu: 9216
    - interface: ethernet1/8
      description: To L2 Eth1/8
      mtu: 9216
    - interface: ethernet1/9
      description: To L2 Eth1/9
      mtu: 9216

loopback_interfaces: &lo
  - interface: loopback0
    description: Routing Loopback
    ip_address: 10.0.0.101
    mask: 32
  - interface: loopback1
    description: VTEP Loopback
    ip_address: 10.100.100.101
    mask: 32

all_layer3_interfaces:
    - *l3
    - *lo
