---
# vars file for spine2

hostname: spine2

layer3_physical_interfaces: &l3
    - name: mgmt0
      ip_address: 10.15.33.12
      mask: 24
      enabled: true
    - name: Ethernet1/1
      description: To L1 Eth1/2
      ip_address: 10.2.2.0
      mask: 31
      mtu: 9216
      enabled: true
      ospf:
        process: UNDERLAY
        area: 0.0.0.0
      pim: true
    - name: Ethernet1/2
      description: To L2 Eth1/2
      ip_address: 10.2.2.2
      mask: 31
      mtu: 9216
      enabled: true
      ospf:
        process: UNDERLAY
        area: 0.0.0.0
      pim: true
    - name: Ethernet1/3
      description: To L3 Eth1/2
      ip_address: 10.2.2.4
      mask: 31
      mtu: 9216
      enabled: true
      ospf:
        process: UNDERLAY
        area: 0.0.0.0
      pim: true

loopback_interfaces: &lo
    - name: loopback0
      description: Routing Loopback
      ip_address: 10.0.0.2
      mask: 32
      enabled: true
      ospf:
        process: UNDERLAY
        area: 0.0.0.0
      pim: true
    - name: loopback250
      description: PIM Anycast RP Loopback
      ip_address: 10.250.250.1
      mask: 32
      enabled: true
      ospf:
        process: UNDERLAY
        area: 0.0.0.0
      pim: true

all_layer3_interfaces: "{{ layer3_physical_interfaces + loopback_interfaces }}"
