---
hostname: L2

layer3_physical_interfaces: &l3
  - interface: ethernet1/1
    description: To S1 Eth1/2
    mode: layer3
    ip_address: 10.1.1.3
    mask: 31
    mtu: 9216
  - interface: ethernet1/2
    description: To S2 Eth1/2
    mode: layer3
    ip_address: 10.2.2.3
    mask: 31
    mtu: 9216
  - interface: ethernet1/3
    description: To S3 Eth1/2
    mode: layer3
    ip_address: 10.3.3.3
    mask: 31
    mtu: 9216
  - interface: ethernet1/4
    description: To S4 Eth1/2
    mode: layer3
    ip_address: 10.4.4.3
    mask: 31
    mtu: 9216

layer2_physical_interfaces: &l2
    - interface: ethernet1/8
      description: To L2 Eth1/8
      mtu: 9216
    - interface: ethernet1/9
      description: To L2 Eth1/9
      mtu: 9216

loopback_interfaces: &lo
  - interface: loopback0
    description: Routing Loopback
    ip_address: 10.0.0.102
    mask: 32
  - interface: loopback1
    description: VTEP Loopback
    ip_address: 10.100.100.102
    mask: 32

all_layer3_interfaces:
    - *l3
    - *lo
